[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
    -D LT_CONTROLLER_UART_BAUD=115200
    -D LT_CONTROLLER_USB_BAUD=115200
    -D LT_CONTROLLER_UART_RX_PIN=12
    -D LT_CONTROLLER_UART_TX_PIN=14
